-- Template for chunked data tables (actual creation happens dynamically)
-- This migration documents the expected schema for data tables
--
-- Data tables are created dynamically in the application via pg_create_data_table()
-- because they have:
-- 1. Dynamic table names based on uploaded files
-- 2. Dynamic column names based on CSV headers
-- 3. Variable number of columns (chunked into groups of 1200)
--
-- Expected schema pattern:
-- CREATE TABLE IF NOT EXISTS _realtime.{table_name} (
--   rowid SERIAL PRIMARY KEY,
--   {patient_col} TEXT NOT NULL,
--   {dynamic_columns...} TEXT
-- );
--
-- Note: For Step 1, we leave dynamic table creation in the app.
-- Future migration: Consider creating an RPC function for dynamic table creation.
